// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiyKxxAF98qSfY1IpjRZz2oewtZxPgJUQ',
    appId: '1:543486540669:web:afed8176d444fbdad0ea14',
    messagingSenderId: '543486540669',
    projectId: 'ancient-world-instagram',
    authDomain: 'ancient-world-instagram.firebaseapp.com',
    storageBucket: 'ancient-world-instagram.appspot.com',
    measurementId: 'G-S9QNR4FKWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT6OHAKr95tpwG48UXm_15guXwVmYrcAs',
    appId: '1:543486540669:android:cc8cb577ae5b2892d0ea14',
    messagingSenderId: '543486540669',
    projectId: 'ancient-world-instagram',
    storageBucket: 'ancient-world-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5-mPkyOTG-GmP-M1lc6sQlvOzzSew_M',
    appId: '1:543486540669:ios:1129d555c080bc47d0ea14',
    messagingSenderId: '543486540669',
    projectId: 'ancient-world-instagram',
    storageBucket: 'ancient-world-instagram.appspot.com',
    iosClientId: '543486540669-mlbt5ri57eq97207g0t62mttj94pnjc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rvpd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr5-mPkyOTG-GmP-M1lc6sQlvOzzSew_M',
    appId: '1:543486540669:ios:1129d555c080bc47d0ea14',
    messagingSenderId: '543486540669',
    projectId: 'ancient-world-instagram',
    storageBucket: 'ancient-world-instagram.appspot.com',
    iosClientId: '543486540669-mlbt5ri57eq97207g0t62mttj94pnjc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rvpd',
  );
}
